name: CI

on:
  push:
    branches:
      - '**'
  workflow_dispatch: # Allow manual triggering

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  analyze:
    name: Lint & Check in PHP v${{ matrix.php-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        php-version:
          - 8.1
          - 8.2
          - 8.3
          - 8.4
          - 8.5
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: shivammathur/setup-php@44454db4f0199b8b9685a5d763dc37cbf79108e1 # v2.36.0
        with:
          php-version: ${{ matrix.php-version }}
          extensions: curl, intl, libxml, mbstring
          coverage: xdebug
      - uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
        with:
          path: vendor/
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
      - run: composer validate --strict
      - run: composer install --no-interaction --no-progress --optimize-autoloader --prefer-dist
      - run: composer lint

  test:
    name: Tests `${{ matrix.package }}` in PHP v${{ matrix.php-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        php-version:
          - 8.1
          - 8.2
          - 8.3
          - 8.4
          - 8.5
        package:
          - cnpj-fmt
          - cnpj-gen
          - cnpj-val
          - cnpj-utils
          - cpf-fmt
          - cpf-gen
          - cpf-val
          - cpf-utils
          - br-utils
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: shivammathur/setup-php@44454db4f0199b8b9685a5d763dc37cbf79108e1 # v2.36.0
        with:
          php-version: ${{ matrix.php-version }}
          extensions: curl, intl, libxml, mbstring
          coverage: xdebug
      - uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
        with:
          path: packages/${{ matrix.package }}/vendor/
          key: ${{ runner.os }}-php-${{ matrix.package }}-${{ hashFiles('composer.lock') }}

      - run: composer validate --strict
        working-directory: packages/${{ matrix.package }}
      - run: composer install --no-interaction --no-progress --optimize-autoloader --prefer-dist
        working-directory: packages/${{ matrix.package }}

      - run: composer test
        working-directory: packages/${{ matrix.package }}
        env:
          API_URL: ${{ vars.BR_UTILS_API_URL }}
          API_TOKEN: ${{ secrets.BR_UTILS_API_TOKEN }}
